apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: frontend
  name: my-webapp
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - image: nginx
        name: nginx

---
apiVersion: v1
kind: Service
metadata:
  labels:
    tier: frontend
  name: front-end-service
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30083
  selector:
    app: my-webapp
  type: NodePort

