apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: prod
  labels:
    app: redis
    role: replica
    tier: msg
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: replica
    tier: msg
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-replica
  namespace: prod
spec:
  selector:
    matchLabels:
      app: redis
      role: replica
      tier: msg
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: replica
        tier: msg
    spec:
      containers:
      - name: replica
        image: redis:alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
