apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-volume
  namespace: prod
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/data
