apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  #  namespace: prod
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurgen: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80

          #After deploy update 1.16 to 1.17
#kubectl set image deployment nginx-deployment nginx=nginx:1.17 --namespace=prod --record -------------> rolling update
# kubectl rollout history -n prod deployment nginx-deployment ------------>view history



